### ISSUE TITLE
ValueError: Resource handles are not convertible to numpy.

### ISSUE THREAD

**Issue by lwyncepu** [RobertLexis/CloudSimPy#13]
python main-makespan.py

2021-06-27 23:37:25.581570: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Jobs number:  10
Tasks number: 93
Task instances number mean:  45.376344086021504
Task instances number std 85.48783652126134
Task instances cpu mean:  0.5264810426540284
Task instances cpu std:  0.10018140357202873
Task instances memory mean:  0.009175121384696406
Task instances memory std:  0.002757219144923028
Task instances duration mean:  74.68815165876777
Task instances duration std:  45.40343044250821
680 0.45179080963134766 62.05685685072286 1.4292964198242561
********** Iteration 0 ************
2021-06-27 23:37:36.427508: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Jobs number:  10
Tasks number: 93
Task instances number mean:  45.376344086021504
Task instances number std 85.48783652126134
Task instances cpu mean:  0.5264810426540284
Task instances cpu std:  0.10018140357202873
Task instances memory mean:  0.009175121384696406
Task instances memory std:  0.002757219144923028
Task instances duration mean:  74.68815165876777
Task instances duration std:  45.40343044250821
680 0.4897310733795166 62.05685685072286 1.4292964198242561
Traceback (most recent call last):
  File "D:/2021/Bin-packing/deepjs/CloudSimPy-master/playground/Non_DAG/launch_scripts/main-makespan2.py", line 132, in <module>
    train()
  File "D:/2021/Bin-packing/deepjs/CloudSimPy-master/playground/Non_DAG/launch_scripts/main-makespan2.py", line 96, in train
    p.start()
  File "D:\anaconda3\envs\deepjs\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\envs\deepjs\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\envs\deepjs\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\envs\deepjs\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\envs\deepjs\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\anaconda3\envs\deepjs\lib\site-packages\tensorflow\python\framework\ops.py", line 763, in __reduce__
    return (convert_to_tensor, (self.numpy(),))
  File "D:\anaconda3\envs\deepjs\lib\site-packages\tensorflow\python\framework\ops.py", line 742, in numpy
    raise ValueError("Resource handles are not convertible to numpy.")
ValueError: Resource handles are not convertible to numpy.

This bug occurs. Can anybody help me with this? 
Thanks!!!

**Comment by taichanghong** [comment]
请问解决了吗？我也遇到了相同的问题。

**Comment by Mond0Bongo** [comment]
兄弟们解决了吗？

**Comment by zzy4566** [comment]
错的一模一样！
